#!/bin/sh

echo "Example of users commands for Linux, mainly Unix"

# Show list of users
cat /etc/passwd

# Create new user
adduser osm

# Set password to user
passwd osm

# Switch to new user
su - osm

# Logout from user
exit

# Add user to wheel group
# can do root shit with sudo command
gpasswd -a osm wheel

# Ownership of any folder
chown -R osm:osm folder/

# Change user home directory
usermod -d /var/ftp/custom_name/ osm

# Postgres example
sudo -u postgres -i
exit